before_script:
  - cd TourGuide

stages:
  - build
  - test-tourguide-and-rewards
  - test-performance

cache:
  paths:
    - .m2/repository
  key: "${CI_COMMIT_REF_SLUG}"

build_job:
  stage: build
  image: maven:3.8.4-eclipse-temurin-17-alpine
  script:
    - cmd /C "mvn -T 1C compile -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true --batch-mode --errors --fail-at-end --show-version"

test-tourguide-and-rewards:
  stage: test-tourguide-and-rewards
  image: maven:3.8.4-eclipse-temurin-17-alpine
  script:
    - cmd /C "mvn -T 1C test -Dtest=TourguideApplicationTests,TestRewardsService,TestTourGuideService -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true --batch-mode --errors --fail-at-end --show-version"

test-performance:
  stage: test-performance
  image: maven:3.8.4-eclipse-temurin-17-alpine
  script:
    - cmd /C "mvn -T 1C test -Dtest=TestPerformance -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true --batch-mode --errors --fail-at-end --show-version"
